export const colors ={
    primary: '#fff',
    buttons: '#2E85FF',
    text: '#fff',
    background: '#fff',
    border: '#1E90FF',
    white: '#fff',
    black: '#000',
    grey: '#ccc',
    red: '#f00',
    lightgrey: '#f2f2f2',
    darkgrey: '#333',
    green: '#00FF00',
    darkgreen: '#006400',
    yellow: '#FFFF00',
    darkyellow: '#FFD700',
    iconColor: '#1E90FF',
    brandColor: '#7216F4',
}